import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/providers/theme-provider";
import { ModeToggle } from "@/components/ToggleMode";
import DropdownSelector from "@/components/DropdownSelector";
import { Toaster } from "@/components/ui/sonner";
import Logo from "@/components/Logo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster />
          <div className="font-[family-name:var(--font-geist-sans)] max-w-screen-xl w-full px-4 mx-auto">
            <div className="flex items-center justify-between p-2 sticky top-0 left-0 z-50 bg-background">
              <Logo />
              <ModeToggle />
            </div>
            <DropdownSelector />

            <main>{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
